<?php

namespace Tests\Feature\Manager\Reviews;

use App\Interfaces\Models\ReviewVoteInterface;
use App\Interfaces\Models\UserInterface;
use App\Models\Review\ReviewVote;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\Response;
use Tests\TestCase;

class VoteTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var UserInterface
     */
    private UserInterface $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->actingAs($this->user);
    }

    /** Publish */
    public function test_manager_can_see_all_comments()
    {
        ReviewVote::factory(10)->create();

        $this->getJson(route('review-votes.index'))
            ->assertJsonCount(10, 'data');
    }

    public function test_manager_can_approve_a_review_comment_successfully()
    {
        $reviewVote = ReviewVote::factory()->create([
            ReviewVoteInterface::APPROVED => false
        ]);

        $this->putJson(route('reviews.votes.approve', $reviewVote), [
            ReviewVoteInterface::APPROVED => true
        ])
            ->assertSuccessful()
            ->assertNoContent();

        $this->assertDatabaseHas(ReviewVoteInterface::TABLE, [
            ReviewVoteInterface::ID => $reviewVote->getId(),
            ReviewVoteInterface::APPROVED => true,
        ]);
    }

    public function test_manager_can_unapprove_a_review_comment_successfully()
    {
        $reviewVote = ReviewVote::factory()->create([
            ReviewVoteInterface::APPROVED => true
        ]);

        $this->putJson(route('reviews.votes.approve', $reviewVote), [
            ReviewVoteInterface::APPROVED => false
        ])
            ->assertSuccessful()
            ->assertNoContent();

        $this->assertDatabaseHas(ReviewVoteInterface::TABLE, [
            ReviewVoteInterface::ID => $reviewVote->getId(),
            ReviewVoteInterface::APPROVED => false,
        ]);
    }

    /**
     * @dataProvider ReviewVoteApproveInvalidData
     */
    public function test_manager_can_not_approve_a_review_comment_with_invalid_data($invalidData)
    {
        $reviewVote = ReviewVote::factory()->create();

        [$ruleName, $payload] = $invalidData();

        $this->putJson(route('reviews.votes.approve', $reviewVote), $payload)
            ->assertStatus(Response::HTTP_UNPROCESSABLE_ENTITY);
    }

    public function ReviewVoteApproveInvalidData()
    {
        return [
            'it fails if review approved field is empty' => [
                function () {
                    return [
                        ReviewVoteInterface::APPROVED,
                        [ReviewVoteInterface::APPROVED => null]
                    ];
                }
            ],
            'it fails if review approved field not be boolean' => [
                function () {
                    return [
                        ReviewVoteInterface::APPROVED,
                        [ReviewVoteInterface::APPROVED => 123]
                    ];
                }
            ]
        ];
    }
}
