<?php

namespace App\Http\Requests\v1\Review;

use App\Base\BaseRequest;

class AddReviewCommentRequest extends BaseRequest
{
    public function rules(): array
    {
        parent::rules(); // TODO: Change the autogenerated stub
    }
}
